# Generated by Django 4.2 on 2023-04-17 15:18

from django.db import migrations, models
import django.db.models.deletion
import library_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0003_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('pub_date', models.DateField()),
                ('no_pages', models.IntegerField()),
                ('book_lang', models.CharField(max_length=400)),
                ('book_dim', models.CharField(max_length=200)),
                ('book_isbn10', models.CharField(max_length=400)),
                ('book_isbn13', models.CharField(default=0, max_length=400)),
                ('book_image', models.ImageField(upload_to=library_app.models.book_upload_to)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_app.author')),
            ],
        ),
    ]
