# Generated by Django 4.2 on 2023-04-17 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0006_alter_address_options_alter_bookissued_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookissued',
            options={'verbose_name_plural': 'Books Issued'},
        ),
        migrations.AlterModelOptions(
            name='bookreturned',
            options={'verbose_name_plural': 'Books Returned'},
        ),
        migrations.AddField(
            model_name='book',
            name='book_issued',
            field=models.BooleanField(default=False),
        ),
    ]
