# Generated by Django 4.2 on 2023-04-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0008_alter_author_name_alter_book_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=400, unique=True),
        ),
    ]
