# Generated by Django 4.2 on 2023-09-04 08:36

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0012_remove_bookissued_books_bookissued_book_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/media/authors'), upload_to=''),
        ),
    ]
