# Generated by Django 4.2 on 2023-09-04 08:43

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0013_alter_author_author_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='authors/'), upload_to=''),
        ),
    ]
