# Generated by Django 4.2 on 2023-09-04 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0014_alter_author_author_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='author_image',
        ),
        migrations.RemoveField(
            model_name='book',
            name='book_image',
        ),
    ]
