# Generated by Django 4.2 on 2023-09-11 09:13

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0017_remove_book_book_image_book_book_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='author_image',
            field=cloudinary.models.CloudinaryField(default='no image', max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
