# Generated by Django 4.2 on 2023-09-11 09:40

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0018_author_author_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_url',
        ),
        migrations.AddField(
            model_name='book',
            name='book_image',
            field=cloudinary.models.CloudinaryField(default='no image', max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
